using System.Net;

namespace veloce.shared.models;

/// <summary>
///     Represents an object to manage a connection.
/// </summary>
public interface ISession<out TEncryption>
    where TEncryption : IEncryptionContext
{
    /// <summary>
    ///     Represents the client remote endpoint.
    /// </summary>
    public IPEndPoint EndPoint { get; }

    /// <summary>
    ///     Represents the encryption values.
    /// </summary>
    public TEncryption Encryption { get; }

    /// <summary>
    ///     Represents the client session id.
    /// </summary>
    /// <remarks>
    ///     <para>This value must be unique and should be generated by the server.</para>
    ///     <para>Unless specified, <see cref="EndPoint" /> acts as such.</para>
    /// </remarks>
    public string Id { get; }
}